name: Run terraform apply

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'hwahae-api/**'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: terraform_plan_apply
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_TOKEN: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
    concurrency:
      group: terraform-execute
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_hostname: "app.terraform.io"
          cli_config_credentials_token: ${{ env.TF_TOKEN }}
          terraform_version: "1.5.7"

      - name: Terraform fmt
        id: fmt
        run: cd hwahae-api && terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: cd hwahae-api && terraform init

      - name: Terraform Validate
        id: validate
        run: cd hwahae-api && terraform validate -no-color

      - name: Terraform Apply
        run: cd hwahae-api && terraform apply -var AWS_ACCESS_KEY_ID=${{env.AWS_ACCESS_KEY_ID}} -var AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}} -var AWS_SESSION_TOKEN=${{env.AWS_SESSION_TOKEN}} -auto-approve
        env:
          TF_INPUT: false
